network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.254.100/26
      gateway4: 192.168.254.1
      nameservers:
          search: [domain.local]
          addresses: [192.168.254.1]
